version: '3.9'
services:
  vector:
    image: timberio/vector:0.30.0-alpine
    ports:
      - 8686:8686
    environment:
      - DD_API_KEY
      - LOG=info
    volumes:
      - ./vector:/etc/vector:ro
